### ISSUE TITLE
Server doesn't respond - iOS 10 / Swift 3

### ISSUE THREAD

**Issue by terwanerik** [thecatalinstan/Criollo#10]
Hi,

Nice project you got going here, i am running into an issue where the server responds the first call, but on refresh just keeps hanging. On the iOS simulator (on macOS) it works beautifully, but when i run it on a device it hangs on the second request.

It even hangs on a 'simple' GET request, e.g. the one in your example:
```
let server = CRHTTPServer()
server.get("/") { (request, response, completionHandler) in
	response.send("Hello world!")
}
server.startListening()
```

Any clues as to why this is happening?

Thanks in advance!

**Comment by thecatalinstan** [comment]
Hi Erik,

Thanks for using Criollo. You have stumbled upon something here :) 👍 

It took me a bit to track it down, but I finally managed to get it fixed. I'll close the issue for now.

Also, if you're using CocoaPods, you should probably update. The current version is 0.4.16.

All the best!
