### ISSUE TITLE
HTTPS support on iOS (Does Criollo support HTTPS?)

### ISSUE THREAD

**Issue by levey** [thecatalinstan/Criollo#11]
Need a web server solution on iOS that supports HTTPS.

**Comment by thecatalinstan** [comment]
Hi @levey, 

Unfortunately not on iOS :(. Yet. It's my next big thing to implement. I hope I'll manage to roll it out towards the end of May.

I'll update this issue when I have more info.

**Comment by Zyphrax** [comment]
@levey You can have a look at Telegraph if you like. It supports HTTPS.
https://github.com/Building42/Telegraph

@thecatalinstan Feel free to look at the internals of Telegraph if you want to add it to Criolio.

**Comment by levey** [comment]
@Zyphrax Thanks, Telegraph looks great, my project is written with Objective-C, I'll try to check is mixing with Swift possible.

**Comment by thecatalinstan** [comment]
@levey, take a look at the development branch: https://github.com/thecatalinstan/Criollo/tree/develop

All you need is already there :)

**Comment by levey** [comment]
@thecatalinstan dude, awesome!
