### ISSUE TITLE
Is there a way that I can work with self signed certificate ?

### ISSUE THREAD

**Issue by sateeshkumardamera** [thecatalinstan/Criollo#16]
I created a self signed certificate and imported to the keychain. Is there a way that this library can read certificate directly from keychain ?

**Comment by thecatalinstan** [comment]
Hi @sateeshkumardamera,

You don't need to read them from the keychain: you can just pass the path to the certificate and key along to your `CRHTTPServer` instance and it will take care of the rest.

Check out the SecureHTTPServer example at [](https://github.com/thecatalinstan/Criollo/tree/develop/Examples/SecureHTTPServer) for more details

As you can notice, HTTPS is not yet on `master`. It is stable, tested and working, but not yet merged into master, so be sure to clone from the `develop` branch if you want to use it.

**Comment by sateeshkumardamera** [comment]
My app is asking for keychain password multiple times. do you know why ?
