### ISSUE TITLE
Is this library multi threaded? (Is this Library thread safe?)

### ISSUE THREAD

**Issue by sateeshkumardamera** [thecatalinstan/Criollo#17]
I am trying to use this library for MacOS. is this library multi threaded ?

**Comment by thecatalinstan** [comment]
Short answer: yes. It actually has a quite complex threading model.

That beeing said, as with any concurrent programming endeavour, you still have to also write thread-safe code. F.x don’t mutate arrays while ennumerating them.

May I aske how you plan to use it and what your specific concern is?

**Comment by sateeshkumardamera** [comment]
I have a MAC app which receives request from browser and forward it to another binding project to get the response and send back the response to browser. If app receives another request before it gets the response, it should goto another thread.

**Comment by thecatalinstan** [comment]
That will happen :)

**Comment by thecatalinstan** [comment]
Alao, depending on your setup you might run into some timeout issues while waiting for the second requeat to complete. Criollo has some pretty aggressive default timeout settings.

Have a look at issue #13 for details on how to configure these options.

**Comment by sateeshkumardamera** [comment]
Ok, but another problem is for single request I made from browser the handler is calling multiple times. Why is that ?

**Comment by thecatalinstan** [comment]
Could you share a sample of the code and a brief description of what is called twice?

**Comment by sateeshkumardamera** [comment]
[self.server get:@"/MyService.svc/Initialize" block:^(CRRequest * _Nonnull request, CRResponse * _Nonnull response, CRRouteCompletionBlock  _Nonnull completionHandler) {
//This is invoking multiple times

 }];

**Comment by thecatalinstan** [comment]
Make sure to finish the response within the block, orherwise the browser assumes it times out and will try again.

Use either [response finish] or [response send:].

**Comment by thecatalinstan** [comment]
@sateeshkumardamera, it still sounds like a time-out issue. I'll try to reproduce your scenario and see what I can come up with. 

Also, when you say you set the timeouts, you did do it as described in issue #13, right?

**Comment by sateeshkumardamera** [comment]
I am doing it as same as you mentioned there #13 . setting this in plist CRConnectionKeepAliveTimeout.

**Comment by thecatalinstan** [comment]
Hey @sateeshkumardamera,

I've been trying to reproduce your case and was unable to. I've created the LongRequest example at  https://github.com/thecatalinstan/Criollo/tree/develop/Examples/LongRequest to that effect and it seems to work as expected. 

As I suspected, it does seem to be a timeout issue, namely when the "long" request takes longer than the outgoing socket is willing to wait for content to be sent. In such a case, most browsers will try to make a second (or third) request, just to make sure and then fail. If you were to try the request using curl, you could see that there is no second call.

Have a look at the example at: https://github.com/thecatalinstan/Criollo/tree/develop/Examples/LongRequest

Let me know how it goes!

**Comment by thecatalinstan** [comment]
Hey @sateeshkumardamera, did it help?

**Comment by sateeshkumardamera** [comment]
Hi,
I was able to figureout the issue. to resolve this issue, I have created the dispatch_async to get the response from another binding project and return it.

Thanks for your help 👍

**Comment by sateeshkumardamera** [comment]
But for each transaction I made to the server, my app is increased by 8MB of memory. any suggestions for this memory leak issue ?

**Comment by thecatalinstan** [comment]
Glad to see it helped :)

About the leaks, I'd look at these two: 

1. https://developer.apple.com/library/content/documentation/Performance/Conceptual/ManagingMemory/Articles/FindingLeaks.html

2. https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/FindingLeakedMemory.html

and maybe also this https://medium.com/rocknnull/ios-gcd-what-the-weak-is-going-on-d5a10fc682a

Have fun!

**Comment by sateeshkumardamera** [comment]
It seems that it is preserving  certificate cache. let me know If i need to do anything manually to release manually ?

**Comment by thecatalinstan** [comment]
Open a new issue if you suspect a bug in the framework and document it appropriately (i.e. explaining specifically what you do and what it leaks, if you know). Remember, the issues are also for other people that will search for answers :)

**Comment by sateeshkumardamera** [comment]
Ok, thats my bad. no leaks in the framework.
But it still retrying the same request sometimes, which is causing problem in my app. I have no clue this issue.
Is there any way that I can find if its a new request or retry request ?

**Comment by sateeshkumardamera** [comment]
Finally, I was able to resolve all the issues in my app including above one.

Only one last issue is app is asking for keychain password again and again. is there something I need to set in plist or some where ?
