### ISSUE TITLE
Keychain locked and prompting for password

### ISSUE THREAD

**Issue by sateeshkumardamera** [thecatalinstan/Criollo#18]
After starting the application and kept idle for sometime. keychain is getting locked and it is prompting for password.
<img width="551" alt="screen-shot-2018-02-22-at-00 19 36" src="https://user-images.githubusercontent.com/855843/36511542-46f728ce-1724-11e8-9c88-fa9a233c7201.png">

**Comment by thecatalinstan** [comment]
Ref: #17
