### ISSUE TITLE
Is there any way that I cam make route path case insensitive ?

### ISSUE THREAD

**Issue by sateeshkumardamera** [thecatalinstan/Criollo#19]
It seems the routes are case sensitive. how can I make them case insensitive?

**Comment by thecatalinstan** [comment]
You can use regex

**Comment by thecatalinstan** [comment]
I think that a more elegant way is to subclass CRHTTPServer and override ‘(NSArray<CRRouteMatchingResult *> *)routesForPath:(NSString*)path method:(CRHTTPMethod)method‘

Just make the path lowercase, then call super.
