### ISSUE TITLE
Self-signed certificate parse error [error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag]

### ISSUE THREAD

**Issue by tepmnthar** [thecatalinstan/Criollo#29]
I've put this certificate under SecureHTTPServer example project, and it works well.
However, if I use it in my own project which imports Criollo from Pod, there are so many unexpected parse errors.
```
7369808704:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1112:
7369808704:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:274:Type=X509
7369808704:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1112:
7369808704:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:536:
7369808704:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1112:
7369808704:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:274:Type=RSA
7369808704:error:04093004:rsa routines:old_rsa_priv_decode:RSA lib:crypto/rsa/rsa_ameth.c:72:
7369808704:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1112:
7369808704:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:274:Type=PKCS8_PRIV_KEY_INFO
7369808704:error:2306F041:PKCS12 routines:PKCS12_key_gen_uni:malloc failure:crypto/pkcs12/p12_key.c:185:
7369808704:error:2307806B:PKCS12 routines:PKCS12_PBE_keyivgen:key gen error:crypto/pkcs12/p12_crpt.c:55:
7369808704:error:06074078:digital envelope routines:EVP_PBE_CipherInit:keygen failure:crypto/evp/evp_pbe.c:126:
7369808704:error:23077073:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 algor cipherinit error:crypto/pkcs12/p12_decr.c:41:
7369808704:error:2306C067:PKCS12 routines:PKCS12_item_i2d_encrypt:encrypt error:crypto/pkcs12/p12_decr.c:144:
7369808704:error:23073067:PKCS12 routines:PKCS12_pack_p7encdata:encrypt error:crypto/pkcs12/p12_add.c:119:
```
Is there still a difference between master and develop branch as mentioned [here](https://github.com/thecatalinstan/Criollo/issues/16).
What should I do to make self-signed cerificate work?

**Comment by thecatalinstan** [comment]
Hi @tepmnthar,

Looking at the warnings, I can see that they are from `openssl`, which tells me two things:

1. You are making an iOS/tvOS app
2. The certificate and or private key is not in the correct format.

I would try the following:

1. Use the certificates and private key pair from the SecureHTTPServer example and see if they work. Let me know if they don't.

2. If it does work, look at your certificate and key pair. Assuming you are trying to use PEM encoded certificate and key, thy should look similar to this.

Certificate:
```
-----BEGIN CERTIFICATE-----
...
(a lot of ASCII characters here)
...
-----END CERTIFICATE-----
```

Key:
```
-----BEGIN PRIVATE KEY-----
...
(a lot of ASCII characters here)
...
-----END PRIVATE KEY-----
```

Let me know if they do look like this.

3. Generate a new certificate and private key pair, like so:

```bash
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -config /private/etc/ssl/openssl.cnf
```
Then use the generated pair (key.pem and cert.pem) to start HTTPS and see if they work. If  it doesn't let me know.

That's all I could come up with for now. Let me know if it helps.

---

Thanks for using Criollo, how do you like it?

Catalin

**Comment by tepmnthar** [comment]
Thank you @thecatalinstan

```
1. Use the certificates and private key pair from the SecureHTTPServer example and see if they work. Let me know if they don't.
2. If it does work, look at your certificate and key pair. Assuming you are trying to use PEM encoded certificate and key, thy should look similar to this.

No, the example key doesn't work. And my self-signed key format is correct.
```

However, I use the same certificate and code (which doesn't work in my main project) in a new established sample test project and it is correct and doesn't throw errors.
So I think there's maybe something conflicted in my main project. I'm trying to figure out the cause. I'll tell you if I find it.

**Comment by thecatalinstan** [comment]
I'll close this as it is something specific to that project and not a general issue.
