### ISSUE TITLE
URL Encoded data parse error

### ISSUE THREAD

**Issue by smbhuin** [thecatalinstan/Criollo#30]
stringByRemovingPercentEncoding called twice while parsing URLEncoded Body Data which is causing problem when there is % in the query param value.

example value is "%25hello"

after parsing body dictionary looks like following:
{
   key1 = value1
   key2 = key2
}

correct one should be

{
   key1 = value1
   key2 = value2
}

**Comment by thecatalinstan** [comment]
Hi @5mb,

Thanks for pointing this out. I’ll look into it as soon as I can. 

Feel free to make a pull request in the meantime if you have a fix in mind.

Thanks for using Criollo.

Best,
Catalin

**Comment by thecatalinstan** [comment]
Hi again!

Turns out this was most likely a copy-paste error, whereby it was using the key instead of the value when the query-string values contained `%`.

`9087a32c103f4a2b81ce2ebbf11b4a66e662d2d9` fixes that.

Thanks for spotting this and thanks for using Criollo.

Best,
Cătălin
