### ISSUE TITLE
Getting started references an old Pod version

### ISSUE THREAD

**Issue by alanionita** [thecatalinstan/Criollo#32]
# Where to find it? 

## Which page?
https://github.com/thecatalinstan/Criollo/wiki/Getting-Started

## Where on the page?
Step 2: Adding Criollo

## Where is the issue?
platform :osx, '10.9'
use_frameworks!
target ‘HelloWorld’ do
    pod 'Criollo', '~> 0.1.7’ // should update to the latest pod version
end

# Why is is a problem?

If you use the Getting started doc in tandem with the examples you'll notice that a few methods are missing. This is solved by updating the podfile and reinstalling the latest version. 

Hope that helps! 👍

Would've made a pull request, but I didn't have that option on the wiki.

**Comment by thecatalinstan** [comment]
Wow. More than a year old. Sorry, man! :(
