### ISSUE TITLE
typo in installation instructions

### ISSUE THREAD

**Issue by mr-fixit** [thecatalinstan/Criollo#33]
This might trip up a newbie or someone moving too fast...

On https://cocoapods.org/pods/Criollo, you say 

Add Criollo to your Podfile. pod 'Criollo', '~> 0.4’

But you mean

Add Criollo to your Podfile. pod 'Criollo', '~> 0.4'

(final char should be an apostrophe, not a curly-back-apostrophe).

**Comment by thecatalinstan** [comment]
Readme file has been updated, however the changes will only appear on cocoapods.org after a new version of the pod has been pushed. It'll take a wile. 

Closing.
