### ISSUE TITLE
Http connections closes after a while

### ISSUE THREAD

**Issue by cflorion** [thecatalinstan/Criollo#34]
Hi :)
The library is really good, very easy to implement and well documented, thanks !

But I'm having a problem. If I leave the server on (an iPad) with a socket connection open (the app in foreground), the other devices cannot connect the server anymore after a while (between 10 or 15 minutes)

If I restart the server (by calling startListening), the connection comes back. II tried putting a timer that restarts the server periodically but this is not a perfect solution since after some tests some client requests fail when they happen at the wrong moment during the restart (even if I call server.stop(immediately: false) )

After each client request, the socket on the server closes with the error:
```
Domain=GCDAsyncSocketErrorDomain Code=4 "Read operation timed out" 
```
Is this normal ? Should'nt it stay open forever ?

Is it something that known ?
Normally, does a socket close after a while ?
Is there a best practice I did not understand ?

Thanks a lot :)

**Comment by cflorion** [comment]
After tests:
It doesn't seem to be the server failing, but I am not sure: A client request fails, then it retries and succeeds. So the problem is more: After a while, some requests fail with no apparent reasons.

**Comment by thecatalinstan** [comment]
Hi @cflorion,

Glad to hear you like Criollo.

Could this be related to issue #13 ?

Let me know if this helps.

Catalin

**Comment by thecatalinstan** [comment]
Closing. Assuming it helped.
