### ISSUE TITLE
CocoaPods error for GCDAsyncSocket.h

### ISSUE THREAD

**Issue by Kaspik** [thecatalinstan/Criollo#45]
Hey! We wanted to switch to modern CocoaPods feature `generate_multiple_pod_projects` (http://blog.cocoapods.org/CocoaPods-1.7.0-beta/) released month(s) ago, and Criollo is the only pod that doesn't support this.

The reason is that `#import "GCDAsyncSocket.h"` is incorrect as it tries to import file from another library without referencing it (correctly it should be `#import <CocoaAsyncSocket/GCDAsyncSocket.h>`).

Are you planning to update lib to support modern CocoaPods features?

Thanks!

**Comment by thecatalinstan** [comment]
Hey @Kaspik, thanks for using Criollo. I’ll definetly look into that sooner rather than later!

**Comment by Kaspik** [comment]
Thank you @thecatalinstan !

I tried to do it on my own, forked your project, tried to get rid of CocoaAsyncSocket submodule, but then it was also failing on openssl, so after almost whole day I gave up. I also opened an issue for Cocoapods that would give me option to skip this new thing for Criollo only, but not supported yet (https://github.com/CocoaPods/CocoaPods/issues/9274)

To repro this issue, just create simple test project `ExampleApp` that uses cocoapods and use for example this Podfile:

```
source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
use_frameworks!

workspace './ExampleApp'
project 'ExampleApp.xcodeproj'

# ignore all warnings from all pods
inhibit_all_warnings!

def extension_includes
    pod 'Crashlytics', '~> 3.14'
    pod 'DeviceUtil', '~> 6.0'
    pod 'SAMKeychain', '~> 1.5'
end

def all_pods
    
    extension_includes

    pod 'Alamofire', '~> 5.0.0-rc.2'
    pod 'DifferenceKit', '~> 1.1'
    pod 'Firebase/Messaging'
    pod 'Firebase/Analytics'
    pod 'LogglyLogger-CocoaLumberjack', '~> 3.0'
    pod 'PromiseKit/CorePromise', '~> 6.11'
    pod 'PubNub', '~> 4.10'
    pod 'SnapKit', '~> 5.0'
    pod 'SwiftEntryKit', '~> 1.1'
    pod 'SwiftLint', '~> 0.35'
end

abstract_target 'App' do
    all_pods
    
    target 'ExampleApp' do
        target 'ExampleApp Tests' do
            inherit! :search_paths
            pod 'Criollo', '~> 0.5'
        end
    end
end
```

Then when running tests (that the only place that uses Criollo), you will get compiler error. It's because of imports. From the blog post:
```
Warning: Switching your project to use multiple .xcodeproj may result in some compiler errors if your pods have relied on importing headers using the quote syntax for its dependencies. For example #import "PDDebugger.h" will no longer work in a pod that depends on PonyDebugger. Instead, we highly suggest you update your headers to correctly import the framework and its associated header: #import <PonyDebugger/PDDebugger.h>. This is intentional since this feature is currently opt-in.
```
http://blog.cocoapods.org/CocoaPods-1.7.0-beta/

Let me know if I can help you somehow, but I feel like getting rid of submodules could be one way. :)

**Comment by Kaspik** [comment]
Morning @thecatalinstan - any update on this? :)

**Comment by Kaspik** [comment]
Almost month later - trying again - Did you have a chance to look at this? :)

**Comment by thecatalinstan** [comment]
Hi @Kaspik,

Thanks for the patience and apologies for taking so long to look into this. Personal reasons have kept me away from my pet projects for a while. Hope this helps anyway.

Best,
Cătălin

**Comment by Kaspik** [comment]
Hey! The solution I built worked, so it wasn’t blocker anymore. Now I can try your pod again from official release.

I hope everything is okay, and thanks! :)

**Comment by thecatalinstan** [comment]
Glad to hear. I haven't released an updated pod yet, I still have some things in the pipeline. 

It is merged on `master` however so, until I update pod, you should be able to get it from there.

**Comment by Kaspik** [comment]
@thecatalinstan Tried master, still not solved. 😢 

The same issue is now happening with openssl as it's also still submodule.
<img width="1125" alt="Screen Shot 2020-05-26 at 10 14 26" src="https://user-images.githubusercontent.com/7204168/82876923-cbd66880-9f39-11ea-8bc5-89708b64d56d.png">

**Comment by thecatalinstan** [comment]
Hey @Kaspik, I saw a mail about having a similar issue with openssl. Is it still current? If it still is, let me know.

Also check out the "SecureHTTPServer" example and see if you have `openssl.framework` in `Pods > Criollo > Criollo > Frameworks`

**Comment by Kaspik** [comment]
Nah, all good, I forgot to add `submodules => true` to the podfile as it's required if you point to master / git repo. :) Thanks!

**Comment by thecatalinstan** [comment]
Awesome! Idk what I'm gonna do with that. I don't particularly like having it as a submodule. I might bring it into the main repo. I really don't want people to have to build openssl from source.

In case you're wondering why I need it at all, it's because iOS and tvOS are not able to parse `der` and `pem`, only `macOS` is, so I use openssl to parse der/pem certificates and keys in order to build a `SecIdentityRef`, which all platforms can understand.

**Comment by Kaspik** [comment]
I think it will need a solution anyways for SPM, because SPM doesn't support submodules, right? And I saw you are working on open branch already.

I have no idea how to work with certificates, link [here](https://stackoverflow.com/a/17295321/4927614) looks like it doesn't need the openssl, but I doubt you wouldn't know about it. :)

**Comment by thecatalinstan** [comment]
Yeah I remember coming across it when I was doing the ssl support. My problem with it was that I wanted the user to able to throw whatever they had at it and it would just work - like nginx or apache do - but the iOS and tvOS Security framework only understands `DER` and `PKCS#12`. 

So I thought, as a courtesy to the user, I'd just do the conversion in Criollo instead of having the them do the conversion on the command line themselves. The HTTPS helper is basically doing the same thing as the oppenssl commands in the SO answer, except it calls the openssl apis directly :) 

PS: SPM is proving annoying to say the least.
