### ISSUE TITLE
mount directory will not response path with folder.

### ISSUE THREAD

**Issue by Whirlwind** [thecatalinstan/Criollo#7]
```
        [_webServer mount:@"/" directoryAtPath:[[self class] localFilePath]];
```
There are some files and directories in the `[[self class] localFilePath]`, for example: `/TestAny/2017-02-14_19-19-33/index.html`

But when I request the url `https://192.168.1.101:8099/TestAny/2017-02-14_19-19-33/index.html` will get not found error: `/index.html not found`.

I check the code : NSString+Criollo.h:69
```
- (NSString *)pathRelativeToPath:(NSString *)path {
    NSUInteger relativePathStart = [self rangeOfString:path options:NSBackwardsSearch].location;
    if ( relativePathStart == NSNotFound ) {
        relativePathStart = 0;
    }
...
}
```

The options is `NSBackwardsSearch` and it will match the last `/` (`/index.html`), not the first `/` ( `/TestAny`).

Is it a bug?

**Comment by thecatalinstan** [comment]
Thanks for taking the time to submit the issue.

The purpose  of `NSBackwardsSearch` is to match "relative paths", so that it only takes into account everything _after_ the base path. 

I don't quite understand what you're trying to do. Specifically, what's the real path (physically) and the published path (the one on the route). May I see more of the surrounding code so that I could get more context?

PS: If you have a fix in mind, **do**  submit a PR and we'll take a look at it together.

**Comment by Whirlwind** [comment]
Here is the code:
```

- (CRHTTPServer *)webServer {
    if (!_webServer) {
        _webServer = [[CRHTTPServer alloc] init];
        _webServer.delegate = self;
        _webServer.isSecure = YES;
        _webServer.certificatePath = [[NSBundle mainBundle] pathForResource:@"server" ofType:@"crt"];
        _webServer.certificateKeyPath = [[NSBundle mainBundle] pathForResource:@"server" ofType:@"key"];
        [_webServer mount:@"/" directoryAtPath:[[self class] localFilePath]];
    }
    return _webServer;
}

+ (NSString *)localFilePath {
    // will return `~/Library/Application Support/MyAppID/Server`
    return [[[NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES) firstObject] stringByAppendingPathComponent:[[NSBundle mainBundle] bundleIdentifier]] stringByAppendingPathComponent:@"Server"];
}
```

Now, I have a file `~/Library/Application Support/MyAppID/Server/TestAny/2017-02-14_19-19-33/index.html`.

So how  should I request this file ?

As my thought, I should use the url `https://192.168.1.101/TestAny/2017-02-14_19-19-33/index.html`, but it said `/index.html not found`.

If I delete the `NSBackwardsSearch`, everything will OK and the file will accessable.

**Comment by thecatalinstan** [comment]
Hey, @Whirlwind I've fixed it. Thanks for tracking it down. 

I hadn't really considered your particular use-case of mounting directly on `/`, so there were a few thingies that slipped by. 

I've also published the changes to CocoaPods. The new version is 0.4.14.
