### ISSUE TITLE
SPM fails with error: could not build Objective-C module 'Criollo'

### ISSUE THREAD

**Issue by philipphofmann** [thecatalinstan/Criollo#89]
Steps to reproduce:
1. Create empty swift project
2. Add Criollo to Package.swift `.package(name:"Criollo", url: "https://github.com/thecatalinstan/Criollo", .branch("master"))`
3. Add `import Criollo` to main.swift
4. Call `swift build`

The build fails with
```
error: could not build Objective-C module 'Criollo'
```

I expect the build to succeed. Also, the latest release `1.0.1` doesn't include the `Package.swift` file so SPM needs to point to `master` which is not optimal. It would be awesome to do a release for the SPM support.

**Comment by thecatalinstan** [comment]
Hi @philipphofmann,

It should work now. Let me know if it doesn't.

> I expect the build to succeed. Also, the latest release 1.0.1 doesn't include the Package.swift file so SPM needs to point to master which is not optimal. It would be awesome to do a release for the SPM support.

I'll make a new release after #90 is done.

Best,
Catalin

**Comment by philipphofmann** [comment]
Yes, it works now for me. Thanks @thecatalinstan for the quick fix 👏
