### ISSUE TITLE
Open ssl build error on new M1 Macbook

### ISSUE THREAD

**Issue by sanjaneya-chwy** [thecatalinstan/Criollo#92]
I use Criollo through SwiftLocalHost server (https://github.com/depoon/SwiftLocalhost) and when I build the project on a new M1 MacBook, I am running into the below error in Xcode. Is this a limitation of using the Criollo library on a M1 Mac (running the apple silicon chip vs the old Macs running on intel chips). 

![Screen Shot 2022-03-07 at 5 08 35 PM](https://user-images.githubusercontent.com/55997758/157126355-06d09370-b0f0-4dcd-9933-8862a21ca242.png)

I found a closed issue similar to the issue I have reported: https://github.com/thecatalinstan/Criollo/issues/69 and https://github.com/thecatalinstan/Criollo/pull/74 for reference. The fix was to remove open SSL but the error I am seeing says , it is looking for open SSL. Please let me know what I am missing

**Comment by bartekpacia** [comment]
Same problem, would love to see it fixed.

**Comment by thecatalinstan** [comment]
I've tagged a new release which should solve this.

https://github.com/thecatalinstan/Criollo/releases/tag/1.1.0
